### ISSUE TITLE
Workaround to avoid deleting ASG in order to "disable" it

### ISSUE THREAD

**Issue by jvsingh** [pzfreo/ox-clo#19]
Item 60 on page 9 of "ox-clo/lab-exercises/02-amazon-ec2-continued.pdf" currently reads:

>  ...you can’t disable an ASG, only delete it.

One workaround might be to change the desired/min/max number of instances to zero. Could save the trouble of deleting and recreating the ASG
![image](https://user-images.githubusercontent.com/6246002/28242503-a1be1452-69a5-11e7-9de8-0a8628096e24.png)

**Comment by pzfreo** [comment]
Done! Good hint, thanks
