### ISSUE TITLE
Incorrect text in exercise 1

### ISSUE THREAD

**Issue by JackieXu** [pzfreo/ox-clo#20]
On the fourth page of https://github.com/pzfreo/ox-clo/blob/master/lab-exercises/01-amazon-ec2-getstarted.pdf, at step 14, it says 'Click **Next: Tag Instance**'. This should be 'Click **Next: Add Tags**'.

Also it might be handy to add some clarification at step 22. Clicking 'Download Key Pair' will prompt the user to either open or save, instead of saving by default.

**Comment by JackieXu** [comment]
The 'Click **Next: Tag Instance**' text is also in the second exercise: https://github.com/pzfreo/ox-clo/blob/master/lab-exercises/02-amazon-ec2-continued.pdf, at step 13. It appears to be already updated in the third exercise.

**Comment by pzfreo** [comment]
Done Thanks
