### ISSUE TITLE
Python print statement/function

### ISSUE THREAD

**Issue by JackieXu** [pzfreo/ox-clo#24]
Some of the Python code examples show `print` used as a statement (e.g. `print 'foo'`), and some examples show it used as a function (e.g. `print('foo')`).

With the movement to the print function in Python 3, I think it might be good to change all usages to the function version.

Side note: This can already be enforced by adding a `from __future__ import print_function`.

**Comment by pzfreo** [comment]
I don't have any plans to switch to Python3 :-)
