### ISSUE TITLE
Virtual Machine Link Doesn't Work

### ISSUE THREAD

**Issue by azaiter** [pzfreo/ox-clo#25]
The link provided in the README for downloading course's virtual machine doesn't work. 

> "The VM for this class is available here: VMWare: https://s3-eu-west-1.amazonaws.com/oxclo/oxclo2016vm.zip"

Returned data: 
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>oxclo2016vm.zip</Key>
<RequestId>1FCCCDEBD8D77F8E</RequestId>
<HostId>
Kfj60TTweyUZXC3vLv/RqY87WEDOlL3omXoMnVPewY7FwC4BkR+iFsZVLf468TD6zt1sdUYhDEs=
</HostId>
</Error>
```

**Comment by jvsingh** [comment]
Updated exercise guide (circulated in class on the first day) has a new link:
https://github.com/pzfreo/ox-clo/blob/master/lab-exercises/00-exercise-guide.pdf
